version: '3'
services:
  postgres:
    image: postgres:15
    container_name: nest-ts-starter-template-db
    restart: always
    ports:
      - 5433:5432
    env_file:
      - .env.development.local
